timeout = 180
merge_queue_enabled = true
report_merge_conflicts = true

[ec2_runners]
runner_group_id = 11
label_prefix = "ec2"
region = "us-east-2"
images = {
    "gha" = "latest-gha-runner-ami",
    "gha_arm64" = "latest-gha-runner-ami-arm64"
}
jit_runner = "organization"
allowed_instances = ["c8a.medium", "t4g.micro"]

[unroll]

[foobar
